### ISSUE TITLE
Overflow error in MediaSourceStream

### ISSUE THREAD

**Issue by AmionSky** [pdeljanov/Sonata#14]
With a certain .flac file I managed to cause this error. In release profile this error does not appear but causes an infinite loop. Note that I'm on Windows 10 with msvc toolchain. The error below is from `sonata-play` but I experienced the same in a separate project that only decodes the file.

```
thread 'main' panicked at 'attempt to subtract with overflow', sonata-core\src\io\media_source_stream.rs:384:12
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:388
  11: core::panicking::panic_fmt
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\panicking.rs:101
  12: core::panicking::panic
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libcore\panicking.rs:56
  13: sonata_core::io::media_source_stream::{{impl}}::read_quad_bytes
             at .\sonata-core\src\io\media_source_stream.rs:384
  14: sonata_core::io::{{impl}}::read_quad_bytes
             at .\sonata-core\src\io\mod.rs:307
  15: sonata_core::io::scoped_stream::{{impl}}::read_quad_bytes
             at .\sonata-core\src\io\scoped_stream.rs:108
  16: sonata_core::io::ByteStream::read_be_u32
             at .\sonata-core\src\io\mod.rs:200
  17: sonata_utils_xiph::flac::metadata::read_picture_block<sonata_core::io::scoped_stream::ScopedStream<mut sonata_core::io::media_source_stream::MediaSourceStream*>>
             at .\sonata-utils-xiph\src\flac\metadata.rs:470
  18: sonata_codec_flac::demuxer::read_all_metadata_blocks
             at .\sonata-codec-flac\src\demuxer.rs:339
  19: sonata_codec_flac::demuxer::{{impl}}::try_new
             at .\sonata-codec-flac\src\demuxer.rs:85
  20: sonata_codec_flac::demuxer::{{impl}}::query::{{closure}}
             at .\sonata-core\src\probe.rs:326
  21: core::ops::function::FnOnce::call_once<closure-0,(sonata_core::io::media_source_stream::MediaSourceStream, sonata_core::formats::FormatOptions*)>
             at C:\Users\csany\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:232
  22: sonata_core::probe::Probe::format
             at .\sonata-core\src\probe.rs:295
  23: sonata_play::main
             at .\sonata-play\src\main.rs:118
  24: std::rt::lang_start::{{closure}}<()>
             at C:\Users\csany\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  25: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:52
  26: std::panicking::try::do_call
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:297
  27: std::panicking::try
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panicking.rs:274
  28: std::panic::catch_unwind
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\panic.rs:394
  29: std::rt::lang_start_internal
             at /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2\/src\libstd\rt.rs:51
  30: std::rt::lang_start<()>
             at C:\Users\csany\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  31: main
  32: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34: BaseThreadInitThunk
  35: RtlUserThreadStart
```

**Comment by pdeljanov** [comment]
Hmm, it's not very obvious what's wrong when looking at the code in question. Is it possible to get a copy of the FLAC file in question? Since it panics when reading the metadata, I really only need the first few MBs if you don't want to share the entire track. Thanks!

**Comment by AmionSky** [comment]
The file that causes the error: https://www.dropbox.com/s/54et3bflntk6uui/error.flac?dl=0

**Comment by pdeljanov** [comment]
I retract that statement, the bug was very obvious LOL. Thanks for providing the file though, I have a fix and can confirm that it works now.

Unfortunately I was in the middle of renaming all the crates so I need to tidy some stuff up before pushing. Should be done by later tomorrow.
